name: TrollXPlus
version: 1.0.0
main: com.trollxplus.TrollXPlus
api-version: 1.19
author: TrollXPlus
description: Advanced troll plugin with GUI interface - Compatible with MC 1.19-1.21+
website: https://github.com/trollxplus

commands:
  troll:
    description: Open the troll GUI
    usage: /troll [player]
    permission: trollxplus.use
  trolladmin:
    description: Admin troll commands
    usage: /trolladmin <reload|toggle>
    permission: trollxplus.admin

permissions:
  trollxplus.use:
    description: Allows using the troll GUI
    default: op
  trollxplus.admin:
    description: Allows admin troll commands
    default: op
  trollxplus.bypass:
    description: Bypass troll effects
    default: false